#!/usr/bin/env bash
# List and add repository topics.
set -e

usage() {
  echo "Usage: gh repo-topic list [<repo>]"
  echo "       gh repo-topic add  [<repo>] <topics>..."
}

repo='{owner}/{repo}'

api() {
  gh api "repos/$repo/topics" -p mercy "$@"
}

encode_topics() {
  local topic
  local i=0
  while read -r topic; do
    [ -n "$topic" ] || continue
    [ "$((i++))" -eq 0 ] || echo -n ','
    printf '"%s"' "$topic"
  done
  for topic; do
    [ "$((i++))" -eq 0 ] || echo -n ','
    printf '"%s"' "$topic"
  done
}

list() {
  api --jq '.names|join("\n")'
}

add() {
  if [ $# -eq 0 ]; then
    usage >&2
    return 1
  fi
  printf '{"names":[%s]}' "$(list | encode_topics "$@")" | \
    api -X PUT --input - --jq '.names|join("\n")'
}

cmd="$1"
[ $# -eq 0 ] || shift 1

case "$cmd" in
  list|add)
    if [ "$1" = "." ]; then
      shift 1
    elif [[ $1 == */* ]]; then
      repo="$1"
      shift 1
    fi
    "$cmd" "$@"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
