#!/bin/bash
# List and add repository topics.
set -e

usage() {
  echo "Usage: gh repo-topic list <repo>"
  echo "       gh repo-topic add  <repo> <topics>..."
}

repo='{owner}/{repo}'

api() {
  gh api "repos/$repo/topics" -p mercy "$@"
}

encode_topics() {
  local topic
  local i=0
  while read -r topic; do
    [ "$((i++))" -eq 0 ] || echo -n ','
    printf '"%s"' "$topic"
  done
  for topic; do
    [ "$((i++))" -eq 0 ] || echo -n ','
    printf '"%s"' "$topic"
  done
}

list() {
  api --jq '.names|join("\n")'
}

add() {
  if [ $# -eq 0 ]; then
    usage >&2
    return 1
  fi
  printf '{"names":[%s]}' "$(list | encode_topics "$@")" | \
    api -X PUT --input - --jq '.names|join("\n")'
}

cmd="$1"
shift 1
case "$cmd" in
  list|add)
    [ "$1" = "." ] || repo="$1"
    shift 1
    "$cmd" "$@"
    ;;
  -h|--help)
    usage
    exit 0
    ;;
  *)
    usage >&2
    exit 1
    ;;
esac
